# baseurl = "https://skyfish81.github.io/"
# languageCode = "en-us"
# title = "skyfish's island"
# # theme = "cocoa"
# theme = "pickles"

# # [params.social]

# # twitter = "skyfish81"
# # github = "skyfish81"
# # email = "skyfish81@gmail.com"
# # linkedin = "ryantss"
# # facebook = "ryantss"
# # instagram = "skyfish81"

baseURL = "https://skyfish81.github.io/"
languageCode = "en-us"
title = "skyfish's island"
enableRobotsTXT = true
enableEmoji = true
# https://www.webpagefx.com/tools/emoji-cheat-sheet/

# Copyright notice. This is displayer in the footer.
# copyright = "&copy; Copyright notice"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "skyfish81"
  facebook = "skyfish81"
  instagram = "skyfish81"
#   googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "skyfish81"
#   gitlab = "Your GitLab username"
#   npm = "Your npm username"
#   codepen = "Your CodePen username"
#   dribbble = "Your Dribbble username"
#   fivehundredpx = "Your 500px username" # 500px
  flickr = "skyfish81"
#   pinterest = "Your Pinterest username"
  tumblr = "skyfiz"
#   vimeo = "Your Vimeo username"
#   youtube = "skyfish81"
  linkedin = "ryantss"
  # Disqus shortname
  disqus = "skyfiz"
  # Google Analytics API key.
  ga_api_key = "UA-116292523-1"
  author = "ryan"
#   authorwebsite = "example.com"
  avatar = "https://pbs.twimg.com/profile_images/977959607933939712/LIxQwmSX_400x400.jpg"
#   contact = "mailto:skyfish81@gmail.com"
#   bio = "simply myself"
    # Short subtitle/tagline. This is displayed in the header.
  subtitle = "code + think + photograph"
  # Logo image. This is displayed ogp image.
#   logo = "/path/to/logo"
#   favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "About"
#     url = "/about"
#     weight = 2

# [[menu.main]]
#     identifier = "theme"
#     name = "/theme"
#     weight = 3

# [[menu.main]]
#     parent = "theme"
#     name = "creating-a-new-theme"
#     url = "/posts/creating-a-new-theme"
#     weight = 1

# [[menu.main]]
#     parent = "theme"
#     name = "migrate-from-jekyll"
#     url = "/posts/migrate-from-jekyll"
#     weight = 2

# [[menu.main]]
#     name = "Tags"
#     url = "/tags"
#     weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"